In [1]:
import numpy as np

# Hlavní funkce: spočítá Householderovu matici P, která převede vektor x do směru vektoru y
def vypocet_householder(x, y):
    x = np.array(x, dtype=float)
    y = np.array(y, dtype=float)

    print("Vstupní vektor x:", x)
    print("Cílový vektor y:", y)

    # 1. Normalizace směrového vektoru y
    y_hat = y / np.linalg.norm(y)
    print("Jednotkový směr vektoru y (ŷ):", y_hat)

    # 2. Výpočet vektoru u = x - ||x||·ŷ
    u = x - np.linalg.norm(x) * y_hat
    print("Vektor u = x - ||x||·ŷ:", u)

    # 3. Pokud x již směřuje jako y, vracíme jednotkovou matici
    if np.linalg.norm(u) < 1e-10:
        print("x již směřuje jako y – vracím jednotkovou matici.")
        return np.eye(len(x))

    # 4. Normalizace vektoru u → v
    v = u / np.linalg.norm(u)
    print("Jednotkový odrazový vektor v:", v)

    # 5. Výpočet Householderovy matice
    P = np.eye(len(x)) - 2 * np.outer(v, v)
    print("Householderova matice P:\n", P)

    # 6. Výpočet výsledného vektoru Px
    Px = P @ x
    print("Výsledek P @ x =", Px)

    # 7. Ověření směru
    Px_norm = Px / np.linalg.norm(Px)
    y_norm = y / np.linalg.norm(y)
    print("Jednotkový směr Px:", Px_norm)
    print("Jednotkový směr y:", y_norm)
    print("Kosinus úhlu mezi Px a y:", np.dot(Px_norm, y_norm))
    print("Směry jsou shodné?", np.allclose(Px_norm, y_norm))

    return P

# Příklad použití – zde můžeš zadat libovolné vektory
x = [1, 2, 3, 4]
y = [4, 3, 2, 1]

# Spuštění výpočtu
vypocet_householder(x, y)


Vstupní vektor x: [1. 2. 3. 4.]
Cílový vektor y: [4. 3. 2. 1.]
Jednotkový směr vektoru y (ŷ): [0.73029674 0.54772256 0.36514837 0.18257419]
Vektor u = x - ||x||·ŷ: [-3. -1.  1.  3.]
Jednotkový odrazový vektor v: [-0.67082039 -0.2236068   0.2236068   0.67082039]
Householderova matice P:
 [[ 0.1 -0.3  0.3  0.9]
 [-0.3  0.9  0.1  0.3]
 [ 0.3  0.1  0.9 -0.3]
 [ 0.9  0.3 -0.3  0.1]]
Výsledek P @ x = [4. 3. 2. 1.]
Jednotkový směr Px: [0.73029674 0.54772256 0.36514837 0.18257419]
Jednotkový směr y: [0.73029674 0.54772256 0.36514837 0.18257419]
Kosinus úhlu mezi Px a y: 0.9999999999999998
Směry jsou shodné? True


array([[ 0.1, -0.3,  0.3,  0.9],
       [-0.3,  0.9,  0.1,  0.3],
       [ 0.3,  0.1,  0.9, -0.3],
       [ 0.9,  0.3, -0.3,  0.1]])

In [1]:
import numpy as np  # Načítám knihovnu NumPy pro práci s vektory a maticemi

# Hlavní funkce: spočítá Householderovu matici P, která převede vektor x do směru vektoru y
def vypocet_householder(x, y):
    x = np.array(x, dtype=float)  # Převedu vstupní vektor x na pole typu float (pro přesnost)
    y = np.array(y, dtype=float)  # Stejně převedu i vstupní vektor y

    print("Vstupní vektor x:", x)  # Vytisknu původní vektor x
    print("Cílový vektor y:", y)   # Vytisknu cílový vektor y

    y_hat = y / np.linalg.norm(y)  # Normalizace směrového vektoru y (jednotkový vektor)
    print("Jednotkový směr vektoru y (ŷ):", y_hat)

    u = x - np.linalg.norm(x) * y_hat  # Výpočet vektoru u = x - ||x|| · ŷ
    print("Vektor u = x - ||x||·ŷ:", u)

    if np.linalg.norm(u) < 1e-10:  # Pokud je u ≈ 0, znamená to že x už směřuje jako y
        print("x již směřuje jako y – vracím jednotkovou matici.")
        return np.eye(len(x))  # Vrátím identitu – žádná změna není potřeba

    v = u / np.linalg.norm(u)  # Normalizace vektoru u → dostanu jednotkový odrazový vektor v
    print("Jednotkový odrazový vektor v:", v)

    P = np.eye(len(x)) - 2 * np.outer(v, v)  # Výpočet Householderovy matice podle vzorce P = I - 2 vvᵗ
    print("Householderova matice P:\n", P)

    Px = P @ x  # Výpočet odraženého vektoru Px = P * x
    print("Výsledek P @ x =", Px)

    Px_norm = Px / np.linalg.norm(Px)  # Normalizace výsledného vektoru Px
    y_norm = y / np.linalg.norm(y)     # Normalizace původního směrového vektoru y

    print("Jednotkový směr Px:", Px_norm)  # Výstup normalizovaného vektoru Px
    print("Jednotkový směr y:", y_norm)    # Výstup normalizovaného vektoru y

    print("Kosinus úhlu mezi Px a y:", np.dot(Px_norm, y_norm))  # Výpočet kosinu úhlu (měřítko podobnosti směrů)
    print("Směry jsou shodné?", np.allclose(Px_norm, y_norm))    # Porovnání, jestli jsou směry téměř stejné (True/False)

    return P  # Vracíme Householderovu matici P

# Příklad použití – zde můžeš zadat libovolné vektory
x = [1, 2, 3, 4]  # Zadání vektoru x
y = [4, 3, 2, 1]  # Zadání vektoru y

vypocet_householder(x, y)  # Spuštění výpočtu


Vstupní vektor x: [1. 2. 3. 4.]
Cílový vektor y: [4. 3. 2. 1.]
Jednotkový směr vektoru y (ŷ): [0.73029674 0.54772256 0.36514837 0.18257419]
Vektor u = x - ||x||·ŷ: [-3. -1.  1.  3.]
Jednotkový odrazový vektor v: [-0.67082039 -0.2236068   0.2236068   0.67082039]
Householderova matice P:
 [[ 0.1 -0.3  0.3  0.9]
 [-0.3  0.9  0.1  0.3]
 [ 0.3  0.1  0.9 -0.3]
 [ 0.9  0.3 -0.3  0.1]]
Výsledek P @ x = [4. 3. 2. 1.]
Jednotkový směr Px: [0.73029674 0.54772256 0.36514837 0.18257419]
Jednotkový směr y: [0.73029674 0.54772256 0.36514837 0.18257419]
Kosinus úhlu mezi Px a y: 0.9999999999999998
Směry jsou shodné? True


array([[ 0.1, -0.3,  0.3,  0.9],
       [-0.3,  0.9,  0.1,  0.3],
       [ 0.3,  0.1,  0.9, -0.3],
       [ 0.9,  0.3, -0.3,  0.1]])