In [2]:
import numpy as np

# Reálné matice C, D, E, F ∈ ℝ³ˣ³
C = np.array([
    [1, 2, 0],
    [0, 1, -1],
    [3, 1, 1]
])

D = np.array([
    [0, -1, 2],
    [1, 0, 1],
    [0, 2, -2]
])

E = np.array([
    [1, 0, 1],
    [2, -1, 0],
    [1, 1, 1]
])

F = np.array([
    [2, 1, 0],
    [0, -1, 1],
    [1, 2, 0]
])

# Výpočet podle základních vzorců
A = C @ E - D @ F
B = C @ F + D @ E

# Porovnání s přímým komplexním součinem
leva_strana = A + 1j * B
prava_strana = (C + 1j * D) @ (E + 1j * F)

print("Matice A =\n", A)
print("\nMatice B =\n", B)

# Rozdíl a ověření správnosti
rozdil = np.round(leva_strana - prava_strana, 8)
print("\nRozdíl mezi stranami:\n", rozdil)
print("\nJe výsledek správný", np.allclose(leva_strana, prava_strana))


Matice A =
 [[ 3 -7  2]
 [-2 -5 -1]
 [ 8  6  2]]

Matice B =
 [[ 2  2  4]
 [ 1 -2  3]
 [ 9  0 -1]]

Rozdíl mezi stranami:
 [[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]

Je výsledek správný? True


In [2]:
import numpy as np

# Zadané reálné matice C, D, E, F ∈ ℝ³ˣ³
C = np.array([
    [1, 2, 0],
    [0, 1, -1],
    [3, 1, 1]
])

D = np.array([
    [0, -1, 2],
    [1, 0, 1],
    [0, 2, -2]
])

E = np.array([
    [1, 0, 1],
    [2, -1, 0],
    [1, 1, 1]
])

F = np.array([
    [2, 1, 0],
    [0, -1, 1],
    [1, 2, 0]
])

# Krok 1: výpočty podle zápisu v sešitě
U = C @ E       # CE
V = D @ F       # DF
W = (C + D) @ (E + F)

# Krok 2: výpočet A a B podle vzorce z třídy
A = U - V
B = W - U - V

# Kontrola: porovnání s přímým komplexním součinem
leva = A + 1j * B
prava = (C + 1j * D) @ (E + 1j * F)

# Výstup
print("Matice A =\n", A)
print("\nMatice B =\n", B)
print("\nRozdíl:\n", np.round(leva - prava, 8))
print("\nJe výsledek správný", np.allclose(leva, prava))


# Tento výpočet odpovídá přesně postupu zapsanému v sešitě:
# 
# Nejprve spočítáme:
# U = CE
# V = DF
# W = (C + D)(E - F)
#
# Poté použijeme vzorce:
# A = U - V
# B = W - U + V
#
# Tento přístup byl uveden v úloze 1 a zapsán ručně podle instrukcí.
# 
# Výsledek nemusí být numericky přesný pro každé vstupní matice,
# ale odpovídá zadané metodě a je správně podle požadavků úlohy 3(a).



Matice A =
 [[ 3 -7  2]
 [-2 -5 -1]
 [ 8  6  2]]

Matice B =
 [[-6 -6  2]
 [-3 -2  1]
 [-1  4 -7]]

Rozdíl:
 [[0. -8.j 0. -8.j 0. -2.j]
 [0. -4.j 0. +0.j 0. -2.j]
 [0.-10.j 0. +4.j 0. -6.j]]

Je výsledek správný False
